<a href="https://colab.research.google.com/github/rehandg/Tute-Dude-Ds-Assignment-2/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1-Working with NumPy
This assignment demonstrates the use of NumPy for array creation, statistical operations, reshaping, slicing, and matrix operations.

In [1]:
import numpy as np

# Question 1

In this section, a 1D NumPy array containing integers from 1 to 20 is created. Statistical operations such as sum, mean, median, and standard deviation are performed.


In [2]:
import numpy as np

# 1D Array
arr1 = np.arange(1, 21)

print("1D Array:")
print(arr1)

print("\nSum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

indices = np.where(arr1 > 10)
print("Indices of elements greater than 10:", indices)

# 2D Array
arr2 = np.arange(1, 17).reshape(4, 4)

print("\n4x4 Array:")
print(arr2)

print("\nTranspose:")
print(arr2.T)

print("\nRow-wise Sum:")
print(np.sum(arr2, axis=1))

print("\nColumn-wise Sum:")
print(np.sum(arr2, axis=0))

# Random 3x3 Arrays
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

print("\nArray A:")
print(a)

print("\nArray B:")
print(b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDot Product:")
print(np.dot(a, b))

# Reshape and Slice
arr3 = np.arange(1, 13).reshape(3, 4)

print("\n3x4 Array:")
print(arr3)

print("\nFirst Two Rows and Last Two Columns:")
print(arr3[:2, -2:])

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements greater than 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)

4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise Sum:
[10 26 42 58]

Column-wise Sum:
[28 32 36 40]

Array A:
[[19  3 20]
 [14 17  3]
 [10 15  9]]

Array B:
[[14 14 19]
 [ 2  9  7]
 [20 19  4]]

Addition:
[[33 17 39]
 [16 26 10]
 [30 34 13]]

Subtraction:
[[  5 -11   1]
 [ 12   8  -4]
 [-10  -4   5]]

Multiplication:
[[266  42 380]
 [ 28 153  21]
 [200 285  36]]

Dot Product:
[[672 673 462]
 [290 406 397]
 [350 446 331]]

3x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Two Rows and Last Two Columns:
[[3 4]
 [7 8]]
